### ISSUE TITLE
Type '"token_separators"' is not assignable to type 'keyof CollectionCreateSchemaWithSrc'.

### ISSUE THREAD

**Issue by StevenH86** [typesense/typesense-js#269]
Hi,

Since updating to 2.0.2 I can no longer compile due to the error below. Cannot figure out what is causing it. I've had to go with skipLibCheck in the meantime. 

Any ideas?

`"typescript": "~5.4.5"`

`[ng]  Type '"token_separators"' is not assignable to type 'keyof CollectionCreateSchemaWithSrc'. [plugin angular-compiler]
[ng]   node_modules/typesense/lib/Typesense/Collection.d.ts:10:84:
[ng]    10 │ ...ollectionCreateSchema, "token_separators" | "symbols_to_index">> {`

Thanks

**Comment by tharropoulos** [comment]
Could you give an example where that error occurs?

**Comment by StevenH86** [comment]
@tharropoulos happens in terminal when trying to compile the app with ng serve. 

I'm guessing it's some dependency conflict, but have no idea which one.

**Comment by tharropoulos** [comment]
It should be a tsc error. Could you try running tsc against your app, and look for the line numbers in the trace

**Comment by StevenH86** [comment]
@tharropoulos 

`node_modules/typesense/lib/Typesense/Collection.d.ts:10:85 - error TS2344: Type '"token_separators" | "symbols_to_index"' does not satisfy the constraint 'keyof CollectionCreateSchemaWithSrc'.
  Type '"token_separators"' is not assignable to type 'keyof CollectionCreateSchemaWithSrc'.

10 export interface CollectionFieldSchema extends Partial<Pick<CollectionCreateSchema, "token_separators" | "symbols_to_index">> {
                                                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in node_modules/typesense/lib/Typesense/Collection.d.ts:10`

**Comment by StevenH86** [comment]
@tharropoulos Thanks, appreciate it.

**Comment by tharropoulos** [comment]
There don't seem to be any type errors in the library as of 2.0.2. Could you provide your `tsconfig.json` so I can replicate it?

**Comment by tharropoulos** [comment]
The PR I posted should take care of this

**Comment by tharropoulos** [comment]
https://github.com/typesense/typesense-js/releases/tag/v2.0.3

**Comment by StevenH86** [comment]
@tharropoulos Thanks for moving so quickly on this. Appreciate it.

**Comment by tharropoulos** [comment]
@StevenH86 Checking to see if the release resolved the issue so we can close this

**Comment by tharropoulos** [comment]
Closing this down since there's been no activity for a while. Feel free to reopen if you have more information. Thanks!

**Comment by StevenH86** [comment]
> [@StevenH86](https://github.com/StevenH86) Checking to see if the release resolved the issue so we can close this

Sorry, I missed this. Yep, it was resolved. Thanks again
